alireviewstuff/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),

]

admin.site.site_header = 'Ali Reviews Stuff | Admin'

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.lander , name='lander'),
    path('about/', views.about , name='about'),
   	path('hidden/', views.hidden , name='hidden'),
    path('review/<int:id>', views.product_review, name='product_review'),
]

core/models.py
from django.conf import settings
from django.db import models

import datetime

# Create your models here.

class products(models.Model):
	user					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	product_name			=			models.CharField(max_length=50, blank=False, null=False, default="")
	mrp						=			models.PositiveIntegerField(default=0)
	selling_price			=			models.PositiveIntegerField(default=0)
	using_since				=			models.DateField(default=datetime.date.today)
	replacement_available	=			models.BooleanField(default=False)
	warranty_years			=			models.PositiveIntegerField(default=0)
	affiliate_url			=			models.URLField(max_length=10000, blank=False, null=False, help_text="Product Affiliate link.")
	number_of_reviews		=			models.PositiveIntegerField(default=0)
	image_url				=			models.URLField(max_length=10000, blank=False, null=False, default='http://placehold.it/230x260')
	
	# delete this later
	image_display			=			models.TextField(max_length=1000, blank=True, null=True)

	# To Avoid spam content
	public_display			=			models.BooleanField(default=False)

	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.product_name)

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = 'Product'
		verbose_name_plural = 'Products'

class reviews(models.Model):
	user					=			models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	product_review			=			models.TextField(max_length=100000, blank=False, null=False, default="12 words cant do justice to this product, wait for full review.")
	product_caption			=			models.TextField(max_length=128, blank=False, null=False, default="Amazing Product... 5/7 would buy again.")
	product_reference		=			models.ForeignKey(products, related_name='all_products', blank=True, null=True, on_delete=models.CASCADE)
	
	# To Avoid spam content
	public_display			=			models.BooleanField(default=False)
	
	timestamp				=			models.DateTimeField(auto_now=False, auto_now_add=True)
	updated					=			models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return(self.product_caption)

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = 'Review'
		verbose_name_plural = 'Reviews'

"""
I N    M Y    M I N D:

the site is populated with products.
each product will have multiple reviews, on different point of times.

>> so one products will have miltiple reviews. <<


"""

core/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404, HttpResponseRedirect, Http404
from django.urls import reverse
from django.conf import settings

from .models import products, reviews
# Create your views here.

def lander(request):
	all_products = products.objects.filter(public_display=True)
	context = {
		'all_products' : all_products,
		"production" : settings.PRODUCTION,

	}
	return render(request, 'lander.html', context)

def hidden(request):
	context = {
		"production" : settings.PRODUCTION,
	}
	return render(request, 'hidden.html', context)

def about(request):
	context = {
		"production" : settings.PRODUCTION,

	}
	return render(request, 'core/about.html', context)


# def for product_review
def product_review(request, id=None):
	product = get_object_or_404(products, id=id)

	all_reviews = None
	if product:
		all_reviews = reviews.objects.filter(product_reference__id = id).exclude(public_display = False)

	context = {
		'product' : product,
		'all_reviews': all_reviews,
		"production" : settings.PRODUCTION,

	}

	return render(request, 'core/productreview.html', context)

core/templates/core/about.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% load customtags %}

{% block title %}About Ali Khundmiri.{% endblock %}

{% block meta_description %}Lets go shopping!{% endblock %}

{% block meta_author %}Ali Khundmiri of AliCoderMaker{% endblock %}

{% block other_meta %}

<meta name="twitter:card" content="summary_large_image">

<meta name="twitter:site" content="@AliCoderMaker">

<meta name="twitter:creator" content="@AliCoderMaker">

<meta property="og:url" content="{{ request.build_absolute_uri }}">

<meta name="twitter:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta property="og:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta name="twitter:title" content="A Curated List of Real Online Income Sources!">

<meta property="og:title" content="A Curated List of Real Online Income Sources!">

<meta name="twitter:description" content="Shopping list of a frugal person. Buy best products in cheap price range.">

<meta property="og:description" content="Shopping list of a frugal person. Buy best products in cheap price range.">

{% endblock %}



{% block head_extras %}
<style type="text/css">
.quote_link{
	color: #E8F1F2
}
.social-section{
	padding: 10px;
	margin: 10px;
	text-align: center;
}</style>
{% endblock %}


{% block content_3 %}
<div class="container">
	<section class="text-section">
		<div class="row">
			<div class="col">
				<img class="card-img" src="http://placehold.it/100x100" alt="Card image">
			</div>
			<div class="col-lg-10">
				<p>Hi, I am <b>Ali Khundmiri</b></p>
				I'm saving money by buying the best products available in the market.				
				Here you will find some products that I have used & and I think you should use too.
			</div>
		</div>
	</section>

	<section class="text-section">
		<h2 class="text-center">About me</h2>
		<br>
		<p>Over the years I have learned that wealth is created by saving every penny. The moment I started saving a bit of money, I thought of buying random stuff, like everyone one else would. But them I thought, do I actually need any thing new?</p>
		<p>This forced me to evaluate everything that I possesed, was it worth replacing?</p>
		<p>Like for example, as of today, I have used my <br>
			 <a href="https://www.apple.com/in/macbook-pro/specs-2015/">macbook pro</a> for almost three years, without a single repair or trouble.<br>
			 <a href="https://amzn.to/2OZWQux">iPhone 6</a> for almost 2 years, without a trouble.<br>
			 <a href="https://amzn.to/2xP72zw">Sennheisers Headphones</a> for almost four years, without it loosing its quality.<br>
			 <a href="https://amzn.to/2RblcCS">Wildcraft bag</a> for almost 2 years, without a single wear or tear.<br>

		</p>
		<p>This made me realise I don't need to buy stuff again and again, if I buy from high quality producers.</p>
		<p>
			Some products are made to make your life easier.
		</p>
		<br>
		<p>
			I firmly believe that once we buy a product, we should make complete use of it, before it wears out.
			<br>
			And I hate it when something breaks or stops functioning mid-use when I have not used it to my full content.
		</p>
		<br>
		<p>
			On the other hand, there are some products which are there by your side for life.
		</p>
		<p>
			As a consumer, I know you would prefer to buy products which are long lasting, worth every penny, and most of all, useful.
		</p>
		<p>
			On this site, I have showcased some such products.
		</p>
		<a href="{% url 'core:lander' %}">Do enjoy these products.</a>
	</section>
	<section class="text-center text-section">
		<blockquote>
			<p>“If we command our wealth, we shall be rich and free. If our wealth commands us, we are poor indeed.”</p>
			<a href="https://en.wikipedia.org/wiki/Edmund_Burke"><p>Edmund Burke</p></a>
		</blockquote>
	</section>
	<section class="text-section text-center">
		<h5>Follow me over the internet</h5>
		<span class=" text-center">
			<a class="social-section" target="_blank" href="https://www.facebook.com/alicodermaker"><i class="fab fa-facebook-f fa-3x"></i></a>
			<a class="social-section" target="_blank" href="https://www.twitter.com/alicodermaker"><i class="fab fa-twitter fa-3x"></i></a> 
			<a class="social-section" target="_blank" href="https://www.instagram.com/alicodermaker"><i class="fab fa-instagram fa-3x"></i></a> 
		</span>
	</section>
</div>
{% endblock %}

core/templates/core/hidden.html
{% extends 'base.html' %}
{% load customtags %}

{% block title %} preview | {{ block.super }}{% endblock %}

{% block meta_description %}Lets go shopping!{% endblock %}

{% block meta_author %}Ali Khundmiri of AliCoderMaker{% endblock %}

{% block other_meta %}

<meta name="twitter:card" content="summary_large_image">

<meta name="twitter:site" content="@AliCoderMaker">

<meta name="twitter:creator" content="@AliCoderMaker">

<meta property="og:url" content="{{ request.build_absolute_uri }}">

<meta name="twitter:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta property="og:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta name="twitter:title" content="A Curated List of Real Online Income Sources!">

<meta property="og:title" content="A Curated List of Real Online Income Sources!">

<meta name="twitter:description" content="Check out the Database of websites which helps you earn money in exchange of real work. No survey sh!t, Just real deal.">

<meta property="og:description" content="Check out the Database of websites which helps you earn money in exchange of real work. No survey sh!t, Just real deal.">

{% endblock %}



{% block head_extras %}
<style type="text/css">
.quote_link{
	color: #E8F1F2
}
</style>
{% endblock %}


{% block content_3 %}
<div class="container">
	<div style="margin-top: 50px"></div>
	
	<h2><i>This product is under review...</i></h2>
	
</div>
{% endblock %}

core/templates/core/productreview.html
{% extends 'base.html' %}
{% load customtags %}

{% block title %} preview | {{ block.super }}{% endblock %}

{% block meta_description %}Lets go shopping!{% endblock %}

{% block meta_author %}Ali Khundmiri of AliCoderMaker{% endblock %}

{% block other_meta %}

<meta name="twitter:card" content="summary_large_image">

<meta name="twitter:site" content="@AliCoderMaker">

<meta name="twitter:creator" content="@AliCoderMaker">

<meta property="og:url" content="{{ request.build_absolute_uri }}">

<meta name="twitter:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta property="og:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta name="twitter:title" content="A Curated List of Real Online Income Sources!">

<meta property="og:title" content="A Curated List of Real Online Income Sources!">

<meta name="twitter:description" content="Check out the Database of websites which helps you earn money in exchange of real work. No survey sh!t, Just real deal.">

<meta property="og:description" content="Check out the Database of websites which helps you earn money in exchange of real work. No survey sh!t, Just real deal.">

{% endblock %}



{% block head_extras %}
<style type="text/css">
.quote_link{
	color: #E8F1F2
}
</style>
{% endblock %}


{% block content_3 %}
<div class="container">
	<div style="margin-top: 50px"></div>
	
	<h2>{{product.product_name}}</h2>
	<p>{{product.using_since}}</p>
	<p>{{product.replacement_available}}</p>
	<p>{{product.warranty_years}}</p>
	<p>{{product.affiliate_url}}</p>
	<p>{{product.number_of_reviews}}</p>
	
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!-- Loading custom tags. core/templatetags/customtags.py -->
{% load customtags %}

<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block meta_description %}{% endblock %}">
	<meta name="author" content="{% block meta_author %}{% endblock %}">
	{% block other_meta %}

	{% endblock %}


	<title>{% block title %}I'm Frugal & bought these stuff | AliReviewStuff{% endblock %}</title> <!-- MAX 70 Chars-->



	<!-- Bootstrap core CSS -->
	<link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- loading fontawesome -->
	<script defer src="{% static 'base/fontawesome/svg-with-js/js/fontawesome-all.js' %}"></script>

	<!-- Custom styles for this template -->
	<link href="{% static 'base/css/heroic-features.css' %}" rel="stylesheet">

	<style type="text/css">
	.emoji-header {
		font-size: 100px !important;
	}
	.emoji-header-center {
		font-size: 100px !important;
		text-align: center;
	}
	.quote_link{
		color: #E8F1F2
	}
	.center {
		display: block;
		margin-left: auto;
		margin-right: auto;
		width: 100%;
	}
	.text-section{
		border-color: #000;
		border-width: 1px;
		box-shadow: 1px 1px 5px #E3E3E3;
		background-color: #fff;
		margin: 25px;
		padding: 50px;
		border-radius: 2px;
	}
	body {
		background-color: #f9f9f9;
		padding-top: 90px;
		position: relative;
	}</style>

	

	{% block head_extras %}
	{% endblock %}

	{% if production %}
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-126731866-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-126731866-1');
	</script>

	{% endif %}
</head>

<body>
	<!-- Navigation -->
	{% include 'navbar.html' %}

	<!-- Page Content -->
	{% block content_1 %}
	{% endblock %}

	<div class="col-lg-9 col-md-9">{% block content_header %}{% endblock %}</div>
	<div class="col-lg-3 col-md-3"></div>

	
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-2"></div>
			<div class="col-lg-6 col-md-8 col-sm-12">
				<!-- content -->
				{% block content_2 %}
				{% endblock %}
			</div>
			<div class="col-lg-3 col-md-3"></div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-lg-1 col-md-2"></div>
			<div class="col-lg-10 col-md-8 col-sm-12">
				<!-- content -->
				{% block content_3 %}
				{% endblock %}
			</div>
			<div class="col-lg-1 col-md-3"></div>
		</div>
	</div>


	<!-- /.container -->

	<!-- Footer -->
	{% include 'footer.html' %}

	<!-- Bootstrap core JavaScript -->
	<script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/footer.html
<footer class="py-5 bg-dark">
	<div class="container">
		<p class="text-center" style="font-size: 60px">👨‍💻</p>
		<!-- /. welcome emoji -->
		<h4 class="text-center text-white">
			Hi, I am Ali.
		</h4>
		<!-- /. my intro -->
		<p class="m-0 text-center text-white">
			I am a Solo Maker and I created, developed & Maintain this website. I go by AliCoderMaker on 
			<a target="_blank" href="https://www.twitter.com/AliCoderMaker">Twitter</a>, 
			<a target="_blank" href="https://www.instagram.com/AliCoderMaker">Instagram</a> and 
			<a target="_blank" href="https://www.facebook.com/AliCoderMaker">Facebook</a>.
			<br>Copyright &copy; Ali Khundmiri 2018
		</p>
		<!-- /. my details -->
	</div>
	<!-- /.container -->
</footer>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Heroic Features - Start Bootstrap Template</title>

	<!-- Bootstrap core CSS -->
	<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="css/heroic-features.css" rel="stylesheet">

</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">Start Bootstrap</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="#">Home
							<span class="sr-only">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Services</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<!-- Page Content -->
	<div class="container">

		<!-- Jumbotron Header -->
		<header class="jumbotron my-4">
			<h1 class="display-3">A Warm Welcome!</h1>
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
			<a href="#" class="btn btn-primary btn-lg">Call to action!</a>
		</header>

		<!-- Page Features -->
		<div class="row text-center">

			<div class="col-lg-3 col-md-6 mb-4">
				<div class="card">
					<img class="card-img-top" src="http://placehold.it/500x325" alt="">
					<div class="card-body">
						<h4 class="card-title">Card title</h4>
						<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
					</div>
					<div class="card-footer">
						<a href="#" class="btn btn-primary">Find Out More!</a>
					</div>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 mb-4">
				<div class="card">
					<img class="card-img-top" src="http://placehold.it/500x325" alt="">
					<div class="card-body">
						<h4 class="card-title">Card title</h4>
						<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
					</div>
					<div class="card-footer">
						<a href="#" class="btn btn-primary">Find Out More!</a>
					</div>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 mb-4">
				<div class="card">
					<img class="card-img-top" src="http://placehold.it/500x325" alt="">
					<div class="card-body">
						<h4 class="card-title">Card title</h4>
						<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
					</div>
					<div class="card-footer">
						<a href="#" class="btn btn-primary">Find Out More!</a>
					</div>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 mb-4">
				<div class="card">
					<img class="card-img-top" src="http://placehold.it/500x325" alt="">
					<div class="card-body">
						<h4 class="card-title">Card title</h4>
						<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
					</div>
					<div class="card-footer">
						<a href="#" class="btn btn-primary">Find Out More!</a>
					</div>
				</div>
			</div>

		</div>
		<!-- /.row -->

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
		</div>
		<!-- /.container -->
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/lander.html
{% extends 'base.html' %}
{% load customtags %}


{% block meta_description %}Lets go shopping!{% endblock %}

{% block meta_author %}Ali Khundmiri of AliCoderMaker{% endblock %}

{% block other_meta %}

<meta name="twitter:card" content="summary_large_image">

<meta name="twitter:site" content="@AliCoderMaker">

<meta name="twitter:creator" content="@AliCoderMaker">

<meta property="og:url" content="{{ request.build_absolute_uri }}">

<meta name="twitter:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta property="og:image" content="https://s3.amazonaws.com/side-projects/rs_directory/media/base/reven_sours_social_image.png">

<meta name="twitter:title" content="A Curated List of Real Online Income Sources!">

<meta property="og:title" content="A Curated List of Real Online Income Sources!">

<meta name="twitter:description" content="Check out the Database of websites which helps you earn money in exchange of real work. No survey sh!t, Just real deal.">

<meta property="og:description" content="Check out the Database of websites which helps you earn money in exchange of real work. No survey sh!t, Just real deal.">

{% endblock %}



{% block head_extras %}
<style type="text/css">
.quote_link{
	color: #E8F1F2
}
</style>
{% endblock %}


{% block content_3 %}
<div class="container">
	<!-- Jumbotron Header -->
	<header class="jumbotron text-section my-4" style="background-color: white">
		<h1>Command <span style="color: red">Our</span> Wealth</h1>
		<p class="lead">I'm Ali, and on this website you can find products which I Love.<br>I have use products on this site for more than a year, and I am glad to share it with you guys. <a href="{% url 'core:about' %}">read more</a></p>
		<!-- <a href="#" class="btn btn-primary btn-lg">Call to action!</a> -->
	</header>
	
	<!-- Page Features -->
	<h2>Products</h2>
	<div class="card-columns text-section">
		
		{% for product in all_products %}
		{% if forloop.counter == 2 %} <!-- This number is the position of advert -->
		<div class="card bg-primary text-white text-center p-3">
			<blockquote class="blockquote mb-0">
				<p>I Endorse only the products and services which I personally use.</p>
				<footer class="blockquote-footer">
					<small>
						<cite title="Source Title"><a class="quote_link" href="twitter.com/AliCoderMaker">Ali Khundmiri</a></cite>
					</small>
				</footer>
			</blockquote>
		</div>
		{% endif %}
		{% if forloop.counter == 4 %} <!-- This number is the position of advert -->
		<div class="card">
			<img class="card-img" src="http://placehold.it/230x260" alt="Card image">
		</div>
		{% endif %}
		<div class="card">

			<img class="card-img-top center" src="{{product.image_url}}" alt="" style="max-width: 150px; margin-top: 40px">
			<!-- {{product.image_display}} -->
			<div class="card-body">
				<p><small style="color: gray">{{product.number_of_reviews}} reviews</small></p>
				<p class="card-text lead">
					{% if product.selling_price == 0 %}
					₹{{product.mrp}}
					{% else %}
					<small>
						<s style="color: gray">₹{{product.mrp}}</s>
					</small>
					<span style="color: red">₹{{product.selling_price}} 😲</span>
					{% endif %}
				</p>
				<h4 class="card-title">{{product.product_name}}</h4>
				<p class="card-text">I bought this {{product.using_since|dayssince}}.
					<br><br> It {% if product.replacement_available == False %} does not {% endif %}came with replacement option {% if product.replacement_available %} and {% else %} but {% endif %} {{product.warranty_years}} year{{ product.warranty_years|pluralize }} of support.
				</p>
			</div>
			<div class="card-footer text-center">
				<a href="{% url 'core:product_review' id=product.id %}" class="btn btn-primary">Read Review</a>
				<br>
				<a href="{{product.affiliate_url}}">Buy Now</a>
			</div>
		</div>
		{% endfor %}
	</div>
	<!-- <section class="text-section text-center">
		<h4>Sponsor your product on this site</h4>
		<a href="">Learn more</a>
	</section> -->
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
	<div class="container">
		<a class="navbar-brand" href="{% url 'core:lander' %}">Command <span style="color: red">Our</span> Wealth</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
<!-- 				<li class="nav-item active">
					<a class="nav-link" href="#">Home
						<span class="sr-only">(current)</span>
					</a>
				</li> -->
				<li class="nav-item">
					<a class="nav-link" href="#">Random Review</a>
				</li>
 				<li class="nav-item">
					<a class="nav-link" href="{% url 'core:about' %}">About me</a>
				</li>
<!--				<li class="nav-item">
					<a class="nav-link" href="#">Contact</a>
				</li> -->
			</ul>
		</div>
	</div>
</nav>